# Generated by Django 3.2.9 on 2023-01-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Name',
            field=models.CharField(default='User', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
    ]
